import { ANCHOR_LEAD, CANONICAL_APPROACH_MIN } from "../../styles";

export const ORCHESTRATOR_BUS_BASE_DISTANCE = ANCHOR_LEAD + 42;
export const ORCHESTRATOR_BUS_SIDE_SPREAD = 18;
export const RECIPROCAL_APPROACH_LEG = ANCHOR_LEAD + 12;
export const FALLBACK_LANE_OFFSET_BASE = 12;
export const FALLBACK_LANE_OFFSET_STEP = 4;
export const CANONICAL_LANE_TOWARD_SOURCE_RATIO = 0.38;
export const CANONICAL_LANE_TOWARD_TARGET_RATIO = 0.62;
export const CANONICAL_APPROACH_DISTANCE = CANONICAL_APPROACH_MIN;
export const MANUAL_INTERSECTION_PENALTY = 130000;
export const MANUAL_BEND_PENALTY = 580;
export const MANUAL_WAYPOINT_PENALTY = 180;
export const FALLBACK_INTERSECTION_PENALTY = 100000;
export const FALLBACK_SIDE_ALIGNMENT_PENALTY_WEIGHT = 40;
export const FALLBACK_OPPOSITE_PAIR_BONUS = -220;
export const FALLBACK_BEND_PENALTY = 480;
export const FALLBACK_SHORT_SEGMENT_THRESHOLD = 18;
export const FALLBACK_SHORT_SEGMENT_PENALTY = 1200;
