import { useTheme } from "@/lib/useTheme";
import { type UseAppStateOptions } from "./appStateTypes";
import {
  useAppStateControllerDerivedState,
} from "./controller/useAppStateController/derivedState";
import { useDesktopNotificationCallback } from "./controller/effects";
import { useScheduleRunPlanSignature } from "./controller/selectors";
import { useEditableDraftChange } from "./controller/mutations";
import { useAppStateControllerHandlers } from "./controller/useAppStateController/handlers";
import { useAppStateControllerRuntime } from "./controller/useAppStateController/runtime";
import { useAppStateControllerState } from "./controller/useAppStateController/state";

export function useAppStateController({ activePanel, setActivePanel }: UseAppStateOptions) {
  const { preference: themePreference, setTheme } = useTheme();
  const {
    initialStateLoading,
    setInitialStateLoading,
    pipelines,
    setPipelines,
    providers,
    setProviders,
    mcpServers,
    setMcpServers,
    storageConfig,
    setStorageConfig,
    runs,
    setRuns,
    smartRunPlan,
    setSmartRunPlan,
    loadingSmartRunPlan,
    setLoadingSmartRunPlan,
    scheduleRunPlan,
    setScheduleRunPlan,
    loadingScheduleRunPlan,
    setLoadingScheduleRunPlan,
    selectedPipelineId,
    setSelectedPipelineId,
    draftWorkflowKey,
    setDraftWorkflowKey,
    aiChatPending,
    setAiChatPending,
    baselineDraft,
    setBaselineDraft,
    isNewDraft,
    setIsNewDraft,
    savingPipeline,
    setSavingPipeline,
    startingRunPipelineId,
    setStartingRunPipelineId,
    stoppingRunPipelineId,
    setStoppingRunPipelineId,
    pausingRunPipelineId,
    setPausingRunPipelineId,
    resumingRunPipelineId,
    setResumingRunPipelineId,
    resolvingApprovalId,
    setResolvingApprovalId,
    notice,
    setNotice,
    noticeTimerRef,
    autosaveTimerRef,
    smartRunPlanRequestIdRef,
    smartRunPlanLastSignatureRef,
    smartRunPlanInFlightSignatureRef,
    smartRunPlanCacheRef,
    scheduleRunPlanRef,
    scheduleRunPlanRequestIdRef,
    scheduleRunPlanInFlightSignatureRef,
    scheduleRunPlanLastSignatureRef,
    scheduleRunPlanCacheRef,
    smartRunPlanRef,
    savingPipelineRef,
    selectedPipelineIdRef,
    draftWorkflowKeyRef,
    mockRunActive,
    setMockRunActive,
    debugPreviewDispatchRouteId,
    setDebugPreviewDispatchRouteId,
    debugEnabled,
    setDebugEnabled,
    desktopNotifications,
    setDesktopNotifications,
    settingsOpen,
    setSettingsOpen,
    canvasDragActive,
    setCanvasDragActive,
    providerOauthStatuses,
    setProviderOauthStatuses,
    providerOauthMessages,
    setProviderOauthMessages,
    runInputModal,
    setRunInputModal,
    runCompletionModal,
    setRunCompletionModal,
    processingRunInputModal,
    setProcessingRunInputModal,
    runtimeInputPromptSeenRef,
    runStatusSnapshotRef,
    inputModalNotificationSignatureRef,
    draft,
    applyDraftChange,
    resetDraftHistory,
    undoDraftChange,
    redoDraftChange,
    canUndo,
    canRedo
  } = useAppStateControllerState();

  const notifyDesktop = useDesktopNotificationCallback({ desktopNotifications });

  const {
    isDirty,
    pipelineSaveValidationError,
    hasOrchestrator,
    selectedPipeline,
    activePipelineRun,
    activeRunPipelineIds,
    startingRun,
    stoppingRun,
    pausingRun,
    resumingRun,
    selectedPipelineRunActive,
    selectedPipelineRealRunActive,
    canPauseActiveRun,
    canResumeActiveRun,
    selectedPipelineEditLocked,
    runPanelToggleDisabled,
    runTooltip,
    runtimeDraft,
    scheduleDraft,
    aiWorkflowKey,
    autosaveStatusLabel
  } = useAppStateControllerDerivedState({
    draft,
    baselineDraft,
    pipelines,
    runs,
    selectedPipelineId,
    draftWorkflowKey,
    startingRunPipelineId,
    stoppingRunPipelineId,
    pausingRunPipelineId,
    resumingRunPipelineId,
    savingPipeline,
    canvasDragActive,
    mockRunActive,
    aiChatPending
  });

  const applyEditableDraftChange = useEditableDraftChange({ applyDraftChange, selectedPipelineEditLocked });

  const {
    selectPipeline,
    handleCreatePipelineDraft,
    handleDeletePipeline,
    handleSavePipeline,
    handleSaveProvider,
    handleCreateMcpServer,
    handleUpdateMcpServer,
    handleDeleteMcpServer,
    handleSaveStorageConfig,
    handleProviderOauthStatusChange,
    handleProviderOauthMessageChange,
    persistRunDraftInputs,
    handleRunPanelDraftStateChange,
    handleStartRun,
    handleStopRun,
    handlePauseRun,
    handleResumeRun,
    handleResolveRunApproval,
    handleForgetSecureInput,
    handleConfirmRunInputModal,
    handleLoadSmartRunPlan,
    handleLoadScheduleRunPlan,
    handleAddStep,
    handleSpawnOrchestrator
  } = useAppStateControllerHandlers({
    pipelines,
    runs,
    draft,
    selectedPipelineId,
    draftWorkflowKey,
    isNewDraft,
    savingPipeline,
    pipelineSaveValidationError,
    isDirty,
    selectedPipelineEditLocked,
    aiChatPending,
    aiWorkflowKey,
    runInputModal,
    startingRunPipelineId,
    stoppingRunPipelineId,
    pausingRunPipelineId,
    resumingRunPipelineId,
    activePipelineRun,
    autosaveTimerRef,
    savingPipelineRef,
    selectedPipelineIdRef,
    draftWorkflowKeyRef,
    smartRunPlanRefs: {
      requestIdRef: smartRunPlanRequestIdRef,
      inFlightSignatureRef: smartRunPlanInFlightSignatureRef,
      lastSignatureRef: smartRunPlanLastSignatureRef,
      cacheRef: smartRunPlanCacheRef
    },
    scheduleRunPlanRefs: {
      requestIdRef: scheduleRunPlanRequestIdRef,
      inFlightSignatureRef: scheduleRunPlanInFlightSignatureRef,
      lastSignatureRef: scheduleRunPlanLastSignatureRef,
      cacheRef: scheduleRunPlanCacheRef
    },
    setActivePanel,
    applyDraftChange,
    applyEditableDraftChange,
    resetDraftHistory,
    setNotice,
    setPipelines,
    setProviders,
    setMcpServers,
    setStorageConfig,
    setSmartRunPlan,
    setLoadingSmartRunPlan,
    setScheduleRunPlan,
    setLoadingScheduleRunPlan,
    setSelectedPipelineId,
    setDraftWorkflowKey,
    setBaselineDraft,
    setIsNewDraft,
    setSavingPipeline,
    setStartingRunPipelineId,
    setStoppingRunPipelineId,
    setPausingRunPipelineId,
    setResumingRunPipelineId,
    setResolvingApprovalId,
    setRuns,
    setProviderOauthStatuses,
    setProviderOauthMessages,
    setRunInputModal,
    setProcessingRunInputModal
  });

  const scheduleRunPlanSignature = useScheduleRunPlanSignature({
    selectedPipelineId,
    scheduleDraft
  });

  useAppStateControllerRuntime({
    activePanel,
    autosaveTimerRef,
    canvasDragActive,
    debugEnabled,
    draft,
    draftWorkflowKey,
    draftWorkflowKeyRef,
    desktopNotifications,
    isDirty,
    notice,
    noticeTimerRef,
    providers,
    pipelineSaveValidationError,
    processingRunInputModal,
    runInputModal,
    runStatusSnapshotRef,
    runs,
    selectedPipelineId,
    selectedPipelineIdRef,
    scheduleDraft,
    scheduleRunPlan,
    scheduleRunPlanRef,
    scheduleRunPlanSignature,
    scheduleRunPlanInFlightSignatureRef,
    scheduleRunPlanLastSignatureRef,
    savingPipeline,
    setDraftWorkflowKey,
    setAiChatPending,
    setBaselineDraft,
    setIsNewDraft,
    setNotice,
    setPipelines,
    setProviders,
    setMcpServers,
    setRunInputModal,
    setRunCompletionModal,
    setRuns,
    setScheduleRunPlan,
    setSelectedPipelineId,
    setSmartRunPlan,
    setStorageConfig,
    setInitialStateLoading,
    runtimeInputPromptSeenRef,
    inputModalNotificationSignatureRef,
    smartRunPlan,
    smartRunPlanRef,
    storageConfig,
    themePreference,
    aiWorkflowKey,
    notifyDesktop,
    handleLoadScheduleRunPlan,
    handleLoadSmartRunPlan,
    handleSavePipeline,
    resetDraftHistory
  });

  return {
    initialStateLoading,
    notice,
    setNotice,
    themePreference,
    setTheme,
    providers,
    storageConfig,
    setStorageConfig,
    pipelines,
    selectedPipelineId,
    setSelectedPipelineId,
    draft,
    draftWorkflowKey,
    baselineDraft,
    isNewDraft,
    hasOrchestrator,
    pipelineSaveValidationError,
    isDirty,
    autosaveStatusLabel,
    runTooltip,
    runPanelToggleDisabled,
    selectedPipelineRunActive,
    selectedPipelineRealRunActive,
    startingRun,
    stoppingRun,
    pausingRun,
    resumingRun,
    canPauseActiveRun,
    canResumeActiveRun,
    selectedPipeline,
    activePipelineRun,
    activeRunPipelineIds,
    startingRunPipelineId,
    stoppingRunPipelineId,
    pausingRunPipelineId,
    resumingRunPipelineId,
    resolvingApprovalId,
    isDirtyDraft: isDirty,
    canUndo,
    canRedo,
    selectedPipelineEditLocked,
    runtimeDraft,
    scheduleDraft,
    runs,
    aiChatPending,
    aiWorkflowKey,
    smartRunPlan,
    loadingSmartRunPlan,
    scheduleRunPlan,
    loadingScheduleRunPlan,
    smartRunPlanRef,
    scheduleRunPlanRef,
    mcpServers,
    mockRunActive,
    setMockRunActive,
    debugPreviewDispatchRouteId,
    setDebugPreviewDispatchRouteId,
    debugEnabled,
    setDebugEnabled,
    desktopNotifications,
    setDesktopNotifications,
    settingsOpen,
    setSettingsOpen,
    canvasDragActive,
    setCanvasDragActive,
    providerOauthStatuses,
    providerOauthMessages,
    handleProviderOauthStatusChange,
    handleProviderOauthMessageChange,
    runInputModal,
    runCompletionModal,
    processingRunInputModal,
    applyDraftChange,
    applyEditableDraftChange,
    undoDraftChange,
    redoDraftChange,
    selectPipeline,
    handleCreatePipelineDraft,
    handleDeletePipeline,
    handleSavePipeline,
    handleSaveProvider,
    handleCreateMcpServer,
    handleUpdateMcpServer,
    handleDeleteMcpServer,
    handleSaveStorageConfig,
    persistRunDraftInputs,
    handleRunPanelDraftStateChange,
    handleStartRun,
    handleStopRun,
    handlePauseRun,
    handleResumeRun,
    handleResolveRunApproval,
    handleForgetSecureInput,
    handleConfirmRunInputModal,
    handleLoadSmartRunPlan,
    handleLoadScheduleRunPlan,
    handleAddStep,
    handleSpawnOrchestrator,
    setRunInputModal,
    setRunCompletionModal
  };
}
